Fix installation paths.
qualisys/qualisys_cpp_sdk pull request #32
Opened 2023-02-22 15:21 UTC by jgoppert

GNUInstallDirs was not defined when target_include_directories was set. This caused it to be blank and the cmake target import failed. User projects importing the cmake target should use include qualisys_cpp_sdk/RTProtocol.h etc.

2023-06-13 06:44 UTC, gorghino commented
I confirm this is required on your Nvidia jetson platforms.
@Capelliexp

2024-11-05 10:40 UTC, MaximilienNaveau commented
I did this PR before I saw your @jgoppert .
I believe this simple change fix your issue as well:
https://github.com/qualisys/qualisys_cpp_sdk/pull/45

2024-11-05 10:54 UTC, MaximilienNaveau commented on CMakeLists.txt
> +        $<INSTALL_INTERFACE:${CMAKE_INSTALL_INCLUDEDIR}>
this can simply be "include"

2024-11-05 10:54 UTC, MaximilienNaveau commented on RTProtocol.cpp
> +                        snprintf(maErrorStr, 1060, "No packet received. %s.", maErrorStr);
should this be part of the PR?

2024-11-07 11:59 UTC, OliverGlandberger commented
Like @MaximilienNaveau pointed out, his approach in [#45](https://github.com/qualisys/qualisys_cpp_sdk/pull/45) also addresses this issue by hardcoding `include` as the install path. However, I think using `include(GNUInstallDirs)` to set `CMAKE_INSTALL_INCLUDEDIR` provides more flexibility by allowing the path to adapt to system-specific conventions.

2024-11-07 12:03 UTC, OliverGlandberger commented on RTProtocol.cpp
> +                        snprintf(maErrorStr, 1060, "No packet received. %s.", maErrorStr);
Using `snprintf(maErrorStr, 1060, "No packet received. %s.", maErrorStr);` to avoid the compiler warning and potentially preventing buffer overflows seems reasonable. 👍 Although I suppose it could be a separate PR.

Maybe it's obvious, but where did a size of `1060` come from?

2024-11-07 13:16 UTC, MaximilienNaveau commented
> Like @MaximilienNaveau pointed out, his approach in [#45](https://github.com/qualisys/qualisys_cpp_sdk/pull/45) also addresses this issue by hardcoding `include` as the install path. However, I think using `include(GNUInstallDirs)` to set `CMAKE_INSTALL_INCLUDEDIR` provides more flexibility by allowing the path to adapt to system-specific conventions.
> 
> If there are any additional insights I should be aware of, please let me know. (:

I believe this PR is better suited to be merge than mine I closed mine in response

2024-11-07 14:54 UTC, nim65s approved these changes
I did the same in https://github.com/nim65s/qualisys_cpp_sdk/commit/c39f643a51d291b358337e4641b85a15d4f72eb2, but forgot to open a PR, so thanks for this !

2024-11-15 20:12 UTC, bahlborn commented on RTProtocol.cpp
> +                        snprintf(maErrorStr, 1060, "No packet received. %s.", maErrorStr);
I agree this should be s separate PR. Also curious where `1060` comes from, as `maErrorStr` is `1024` characters.

2024-11-15 20:14 UTC, bahlborn requested changes
Move sprintf->snprintf change to another PR. 
Verify use of 1060 as buffer size.

2025-02-19 14:23 UTC, OliverGlandberger commented
Hey! I just wanted to mention that we've taken these changes from this fork of yours and create [THIS PR](https://github.com/qualisys/qualisys_cpp_sdk/pull/65). Feel free to have a look at it. Note that the "sprintf" issues have already been fixed.

Once the PR is approved and merged then we can close this one. Thank you very much for the input. :)

2025-02-19 16:51 UTC, MaximilienNaveau approved these changes

2025-02-19 18:57 UTC, jgoppert commented
I simplified this PR and just make the GNUInstallDirs fix.

2025-02-19 18:59 UTC, jgoppert commented on RTProtocol.cpp
> +                        snprintf(maErrorStr, 1060, "No packet received. %s.", maErrorStr);
I think setting it to 1024 would be fine.

2025-02-19 19:04 UTC, jgoppert commented
@OliverGlandberger  @nim65s  maybe we can make the other changes another PR and close this one for simplicity?

2025-02-19 19:45 UTC, jgoppert commented
If it makes more sense to take it all together with @OliverGlandberger  I'm fine with that. Just happy to see it merged :-)

2025-02-20 08:14 UTC, closed without merging