Added time out parameter to Save Capture with default of 30 seconds
qualisys/qualisys_cpp_sdk pull request #42
Opened 2024-06-28 10:34 UTC by ulvs

Issue
Send command has a default timeout of 5 seconds. This can be to short time for a save.

Solution
Added a timeout parameter to the SaveCapture command so the timeout can be configured. To keep compability with old code the default value is set to 30 seconds.

2024-07-01 22:43 UTC, bahlborn commented on RTProtocol.h
> +    bool       SaveCapture(const char* pFileName, bool bOverwrite, char* pNewFileName = nullptr, int nSizeOfNewFileName = 0, int nTimeout = 30000000); //Default timeout is 30 seconds
suggestion: use a `const` similar to `cWaitForDataTimeout`

2024-07-01 22:44 UTC, bahlborn requested changes
see comment

2024-07-01 23:01 UTC, bahlborn approved these changes

2024-07-02 04:41 UTC, OliverGlandberger approved these changes

2024-07-02 20:24 UTC, merged